Feat: Numbas updated with polymorphic association
doubtfire-lms/doubtfire-api pull request #445
Opened 2024-09-08 03:22 UTC by satikaj

# Description

Latest commit introduces polymorphic association to task comments. Currently, task comments can belong to either Scorm test attempts or Overseer assessments.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Unit tests passed. Comments display as usual in the frontend.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation if appropriate
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have created or extended unit tests to address my new additions
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-09-24 01:00 UTC, macite requested changes
Looking super close - the Task Comment table is huge, so I think we can optimise the update... see the comment. @satikaj do you have time to make these changes?

2024-09-24 01:00 UTC, macite commented on db/migrate/20240601103707_add_polymorphic_association_to_comment.rb
> +      if comment.commentable_id.present?
You should be able to do this with a where - TaskComment.where('NOT commendable_id IS NULL').find_each

2024-09-24 01:00 UTC, macite commented on db/migrate/20240601103707_add_polymorphic_association_to_comment.rb
> +        comment.update(commentable_type: 'OverseerAssessment')
I think you could then do update all... something like this:

```suggestion
     TaskComment.where('NOT commendable_id IS NULL').in_batches.update_all(commentable_type: 'OverseerAssessment')
```

2024-09-26 02:56 UTC, satikaj commented on db/migrate/20240601103707_add_polymorphic_association_to_comment.rb
> +      if comment.commentable_id.present?
I've made the changes now, Andrew

2024-10-25 05:08 UTC, merged